apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hr2fpz655-python
  janus-idp.io/tekton: hr2fpz655-python
  backstage.io/kubernetes-id: hr2fpz655-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hr2fpz655-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
